
name: 'Code Style'

on: [ push, pull_request ]

jobs:
  code-style:
    name: Code Style Check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Check code style
        run: |
          make lint
