
name: 'Unit Test'

on: [ push, pull_request ]

jobs:

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php:
          - '8.1'
          - '8.2'
        typo3:
          - '12.4'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: nanasess/setup-php@v3
        with:
          php-version: ${{ matrix.php }}

      - name: Test on PHP ${{ matrix.php }} on TYPO3 ${{ matrix.typo3 }}
        run: |
          composer remove typo3/cms-core typo3/cms-extbase typo3/cms-frontend
          composer require "typo3/cms-core:^${{ matrix.typo3 }}" "typo3/cms-extbase:^${{ matrix.typo3 }}" "typo3/cms-frontend:^${{ matrix.typo3 }}"
          make unit
